image: atlassian/default-image:3

pipelines:
  # Automated pipeline for syncing Bitbucket repository with its GitHub mirror, ensuring real-time updates across platforms
  branches:
    '*':
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:unes-ecommerce/adobe-eds.git
            - cd adobe-eds.git
            - git push --mirror git@github.com:ICTdigitalUnes/unes-corp-aem.git